/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ShiftDAO;
import model.Contract;
import model.ContractJob;
import model.ContractJobShift;
import model.Shift;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import static javax.swing.SwingUtilities.isRightMouseButton;

/**
 *
 * @author HoangHoangTuan
 */
public class AddShiftFrm extends JFrame {

    private static final Logger logger = Logger.getLogger(AddShiftFrm.class.getName());
    private CreateContractFrm createContractFrm;
    private Contract contract;
    private ContractJob contractJob;
    private ArrayList<Shift> shifts = new ArrayList<>();
    private ArrayList<ContractJobShift> contractJobShifts = new ArrayList<>();
    DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm");

    /**
     * Creates new form AddShiftFrm
     */
    public AddShiftFrm(CreateContractFrm createContractFrm, Contract contract, ContractJob contractJob) {
        this.createContractFrm = createContractFrm;
        this.contract = contract;

        int index = this.contract.getContractJobs().indexOf(contractJob);
        if (index != -1) {
            this.contractJob = this.contract.getContractJobs().get(index);
        } else {
            this.contractJob = contractJob;
        }
        this.contractJobShifts = new ArrayList<>(this.contractJob.getContractJobShifts());

        initComponents();
        this.setLocationRelativeTo(null);
        initLGoodDatePicker();

        DefaultTableModel tableModel = (DefaultTableModel) tblContractJobShift.getModel();
        tableModel.setRowCount(0);

        int cnt = 0;
        for (ContractJobShift cjs : this.contractJobShifts) {
            tableModel.addRow(new Object[]{
                    ++cnt,
                    cjs.getShift().getWorkingDate().format(dateFormatter),
                    cjs.getShift().getStartTime().format(timeFormatter),
                    cjs.getShift().getEndTime().format(timeFormatter),
                    cjs.getRequiredWorkers(),
                    cjs.getAgreedWage()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblContractJobShift = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRequiredWorker = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAgreedWage = new javax.swing.JTextField();
        btnSearchShift = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblShift = new javax.swing.JTable();
        lblErrorWorkingDate = new javax.swing.JLabel();
        lblErrorStartTime = new javax.swing.JLabel();
        lblErrorEndTime = new javax.swing.JLabel();
        lblErrorRequiredWorker = new javax.swing.JLabel();
        lblErrorAgreeWage = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAddShift = new javax.swing.JButton();
        pkrWorkingDate = new com.github.lgooddatepicker.components.DatePicker();
        pkrStartTime = new com.github.lgooddatepicker.components.TimePicker();
        pkrEndTime = new com.github.lgooddatepicker.components.TimePicker();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm ca làm - ĐV: " + this.contractJob.getJob().getJobName());

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách ca làm đã đăng ký"));

        tblContractJobShift.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "STT", "Ngày làm", "Giờ bắt đầu", "Giờ kết thúc", "Số nhân công", "Đơn giá"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tblContractJobShift.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblContractJobShiftMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblContractJobShift);
        if (tblContractJobShift.getColumnModel().getColumnCount() > 0) {
            tblContractJobShift.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm ca làm mới"));

        jLabel4.setText("Ngày làm:");

        jLabel5.setText("Giờ bắt đầu:");

        jLabel6.setText("Giờ kết thúc:");

        jLabel7.setText("Số nhân công:");

        jLabel8.setText("Đơn giá:");

        btnSearchShift.setText("Tìm ca");
        btnSearchShift.addActionListener(this::btnSearchShiftActionPerformed);

        tblShift.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "STT", "Ngày làm", "Giờ bắt đầu", "Giờ kết thúc", "Chọn"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean[]{
                    false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblShift);
        if (tblShift.getColumnModel().getColumnCount() > 0) {
            tblShift.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        lblErrorWorkingDate.setText(" ");
        lblErrorWorkingDate.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        lblErrorWorkingDate.setForeground(new java.awt.Color(255, 0, 0));

        lblErrorStartTime.setText(" ");
        lblErrorStartTime.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        lblErrorStartTime.setForeground(new java.awt.Color(255, 0, 0));

        lblErrorEndTime.setText(" ");
        lblErrorEndTime.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        lblErrorEndTime.setForeground(new java.awt.Color(255, 0, 0));

        lblErrorRequiredWorker.setText(" ");
        lblErrorRequiredWorker.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        lblErrorRequiredWorker.setForeground(new java.awt.Color(255, 0, 0));

        lblErrorAgreeWage.setText(" ");
        lblErrorAgreeWage.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        lblErrorAgreeWage.setForeground(new java.awt.Color(255, 0, 0));

        jLabel9.setText("Để thêm các ca làm đã chọn, click Thêm.");

        btnAddShift.setText("Thêm");
        btnAddShift.addActionListener(this::btnAddShiftActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel7)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtRequiredWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(lblErrorRequiredWorker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel8)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtAgreedWage, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(lblErrorAgreeWage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane2)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel4)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(pkrWorkingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(lblErrorWorkingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblErrorStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel5)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(pkrStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel6)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(pkrEndTime, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                                                                        .addComponent(lblErrorEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnSearchShift, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel9)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnAddShift)))
                                                .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6)
                                        .addComponent(btnSearchShift)
                                        .addComponent(pkrWorkingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pkrStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pkrEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblErrorWorkingDate)
                                        .addComponent(lblErrorStartTime)
                                        .addComponent(lblErrorEndTime))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtRequiredWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(txtAgreedWage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblErrorRequiredWorker)
                                        .addComponent(lblErrorAgreeWage))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(btnAddShift))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSave.setText("Lưu đầu việc");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnBack.setText("Quay lại");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnSave)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnBack)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSave)
                                        .addComponent(btnBack))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchShiftActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnSearchShiftActionPerformed
        // TODO add your handling code here:
        lblErrorWorkingDate.setText(" ");
        lblErrorStartTime.setText(" ");
        lblErrorEndTime.setText(" ");

        boolean isValid = true;

        LocalDate workingDate = pkrWorkingDate.getDate();
        if (workingDate == null) {
            lblErrorWorkingDate.setText("*Vui lòng nhập ngày làm việc");
            isValid = false;
        }

        LocalTime startTime = pkrStartTime.getTime();
        if (startTime == null) {
            lblErrorStartTime.setText("*Vui lòng nhập giờ bắt đầu");
            isValid = false;
        }

        LocalTime endTime = pkrEndTime.getTime();
        if (endTime == null) {
            lblErrorEndTime.setText("*Vui lòng nhập giờ kết thúc");
            isValid = false;
        }
//
        if (startTime != null && endTime != null && !endTime.isAfter(startTime)) {
            lblErrorStartTime.setText("*Giờ kết thúc phải sau giờ bắt đầu");
            lblErrorEndTime.setText("*Giờ kết thúc phải sau giờ bắt đầu");
            isValid = false;
        }

        if (!isValid) {
            return;
        }

        Shift shift = new Shift(0, workingDate, startTime, endTime);
        ShiftDAO shiftDAO = new ShiftDAO();
        this.shifts = shiftDAO.searchShift(shift);

        DefaultTableModel tableModel = (DefaultTableModel) tblShift.getModel();
        tableModel.setRowCount(0);

        int cnt = 0;
        for (Shift s : this.shifts) {
            tableModel.addRow(new Object[]{
                    ++cnt,
                    s.getWorkingDate().format(dateFormatter),
                    s.getStartTime().format(timeFormatter),
                    s.getEndTime().format(timeFormatter),
                    false
            });
        }
    }//GEN-LAST:event_btnSearchShiftActionPerformed

    private void btnAddShiftActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAddShiftActionPerformed
        // TODO add your handling code here:
        String requiredWorkerString = txtRequiredWorker.getText();
        String agreedWageString = txtAgreedWage.getText();

        lblErrorRequiredWorker.setText(" ");
        lblErrorAgreeWage.setText(" ");

        boolean isValid = true;

        int requiredWorkers = 0;
        if (requiredWorkerString.isEmpty()) {
            lblErrorRequiredWorker.setText("*Vui lòng nhập số nhân công");
            isValid = false;
        } else {
            try {
                requiredWorkers = Integer.parseInt(requiredWorkerString);
                if (requiredWorkers <= 0) {
                    lblErrorRequiredWorker.setText("*Số nhân công phải lớn hơn 0");
                    isValid = false;
                }
            } catch (Exception e) {
                lblErrorRequiredWorker.setText("*Số nhân công phải là số nguyên");
                isValid = false;
            }
        }

        double agreedWage = 0;
        if (agreedWageString.isEmpty()) {
            lblErrorAgreeWage.setText("*Vui lòng nhập đơn giá");
            isValid = false;
        } else {
            try {
                agreedWage = Double.parseDouble(agreedWageString);
                if (agreedWage <= 0) {
                    lblErrorAgreeWage.setText("*Đơn giá phải lớn hơn 0");
                    isValid = false;
                }
            } catch (Exception e) {
                lblErrorAgreeWage.setText("*Đơn giá phải là số");
                isValid = false;
            }
        }

        if (!isValid) {
            return;
        }

        DefaultTableModel tableModelShifts = (DefaultTableModel) tblShift.getModel();
        DefaultTableModel tableModelContractJobShifts = (DefaultTableModel) tblContractJobShift.getModel();

        ArrayList<ContractJobShift> existedShifts = new ArrayList<>();
        ArrayList<ContractJobShift> selectedShifts = new ArrayList<>();

        for (int i = 0; i < tableModelShifts.getRowCount(); ++i) {
            if ((boolean) tableModelShifts.getValueAt(i, 4)) {
                ContractJobShift selectedShift = new ContractJobShift(
                        i,
                        requiredWorkers,
                        agreedWage,
                        this.shifts.get(i)
                );

                selectedShifts.add(selectedShift);
                if (this.contractJobShifts.contains(selectedShift)) {
                    tableModelShifts.setValueAt(false, i, 4);
                    existedShifts.add(selectedShift);
                }
            }
        }

        if (selectedShifts.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ít nhất một ca làm để thêm.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else if (existedShifts.isEmpty()) {
            for (ContractJobShift cjs : selectedShifts) {
                tableModelShifts.setValueAt(false, cjs.getId(), 4);

                this.contractJobShifts.add(cjs);
                tableModelContractJobShifts.addRow(new Object[]{
                        tableModelContractJobShifts.getRowCount() + 1,
                        cjs.getShift().getWorkingDate().format(dateFormatter),
                        cjs.getShift().getStartTime().format(timeFormatter),
                        cjs.getShift().getEndTime().format(timeFormatter),
                        cjs.getRequiredWorkers(),
                        cjs.getAgreedWage()
                });
            }
        } else {
            String message = "Ca làm số " + existedShifts.stream().map(cjs -> String.valueOf(cjs.getId() + 1)).collect(Collectors.joining(", ")) + " đã được thêm trước đó.";
            JOptionPane.showMessageDialog(this, message, "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAddShiftActionPerformed

    private void btnSaveActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (this.contractJobShifts.isEmpty()) {
            if (JOptionPane.showConfirmDialog(this, "Xác nhận không thêm ca làm cho đầu việc này?\nĐầu việc này sẽ bị xoá.", "Xác nhận", JOptionPane.YES_NO_OPTION) == 0) {
                this.contract.getContractJobs().remove(this.contractJob);
                this.createContractFrm.reloadTblContractJob();
                this.dispose();
            }
            return;
        } else if (!this.contract.getContractJobs().contains(this.contractJob)) {
            this.contract.getContractJobs().add(this.contractJob);
        }

        this.contractJob.setContractJobShifts(this.contractJobShifts);
        this.createContractFrm.reloadTblContractJob();
        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblContractJobShiftMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContractJobShiftMousePressed
        // TODO add your handling code here:
        int row = tblContractJobShift.rowAtPoint(evt.getPoint());

        if (row == -1) {
            return;
        }

        tblContractJobShift.setRowSelectionInterval(row, row);

        if (isRightMouseButton(evt)) {
            JPopupMenu popupMenu = new JPopupMenu();
            JMenuItem itemDelete = new JMenuItem("Xoá");
            popupMenu.add(itemDelete);
            popupMenu.show(tblContractJobShift, evt.getX(), evt.getY());

            itemDelete.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    if (JOptionPane.showConfirmDialog(AddShiftFrm.this, "Bạn có xác nhận xoá ca làm này?", "Xác nhận", JOptionPane.YES_NO_OPTION) == 0) {
                        deleteShiftAtRow(row);
                    }
                }
            });
        }
    }//GEN-LAST:event_tblContractJobShiftMousePressed

    private void deleteShiftAtRow(int row) {
        this.contractJobShifts.remove(row);
        reloadTblContractJobShift();
    }

    private void reloadTblContractJobShift() {
        DefaultTableModel tableModel = (DefaultTableModel) tblContractJobShift.getModel();
        tableModel.setRowCount(0);

        int cnt = 0;
        for (ContractJobShift cjs : this.contractJobShifts) {
            tableModel.addRow(new Object[]{
                    ++cnt,
                    cjs.getShift().getWorkingDate().format(dateFormatter),
                    cjs.getShift().getStartTime().format(timeFormatter),
                    cjs.getShift().getEndTime().format(timeFormatter),
                    cjs.getRequiredWorkers(),
                    cjs.getAgreedWage()
            });
        }
    }

    private void initLGoodDatePicker() {
        com.github.lgooddatepicker.components.DatePickerSettings dateSettings = pkrWorkingDate.getSettings();
        LocalDate today = LocalDate.now();
        LocalDate nextMonday = today.with(java.time.temporal.TemporalAdjusters.next(java.time.DayOfWeek.MONDAY));
        LocalDate nextSunday = nextMonday.plusDays(6);
        dateSettings.setDateRangeLimits(nextMonday, nextSunday);
        dateSettings.setFormatForDatesCommonEra(dateFormatter);

        com.github.lgooddatepicker.components.TimePickerSettings startTimeSettings = pkrStartTime.getSettings();
        startTimeSettings.generatePotentialMenuTimes(
                com.github.lgooddatepicker.components.TimePickerSettings.TimeIncrement.OneHour,
                LocalTime.of(0, 0),
                LocalTime.of(23, 0)
        );
        startTimeSettings.setFormatForDisplayTime(timeFormatter);
        startTimeSettings.setFormatForMenuTimes("HH:mm");

        com.github.lgooddatepicker.components.TimePickerSettings endTimeSettings = pkrEndTime.getSettings();
        ArrayList<LocalTime> desiredTimes = new ArrayList<>();
        for (int hour = 0; hour < 24; ++hour) {
            LocalTime time = LocalTime.of(hour, 50);
            desiredTimes.add(time);
        }
        endTimeSettings.generatePotentialMenuTimes(desiredTimes);
        endTimeSettings.setFormatForDisplayTime(timeFormatter);
        endTimeSettings.setFormatForMenuTimes("HH:mm");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddShift;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchShift;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblErrorAgreeWage;
    private javax.swing.JLabel lblErrorEndTime;
    private javax.swing.JLabel lblErrorRequiredWorker;
    private javax.swing.JLabel lblErrorStartTime;
    private javax.swing.JLabel lblErrorWorkingDate;
    private com.github.lgooddatepicker.components.TimePicker pkrEndTime;
    private com.github.lgooddatepicker.components.TimePicker pkrStartTime;
    private com.github.lgooddatepicker.components.DatePicker pkrWorkingDate;
    private javax.swing.JTable tblContractJobShift;
    private javax.swing.JTable tblShift;
    private javax.swing.JTextField txtAgreedWage;
    private javax.swing.JTextField txtRequiredWorker;
    // End of variables declaration//GEN-END:variables
}
