/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ContractDAO;
import model.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author HoangHoangTuan
 */
public class ConfirmContractFrm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConfirmContractFrm.class.getName());
    private CreateContractFrm createContractFrm;
    private Contract contract;
    DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm");

    /**
     * Creates new form CreateContractFrm
     */
    public ConfirmContractFrm(CreateContractFrm createContractFrm, Contract contract) {
        this.createContractFrm = createContractFrm;
        this.contract = contract;
        initComponents();
        this.setLocationRelativeTo(null);


        Customer customer = this.contract.getCustomer();
        lblCustomerFullName.setText(customer.getFullName());
        lblCustomerIdCard.setText(customer.getIdCard());
        lblCustomerAddress.setText(customer.getAddress());
        lblCustomerEmail.setText(customer.getEmail());
        lblCustomerPhone.setText(customer.getPhone());
        lblCustomerType.setText(customer.getType());

        if (customer.getDateOfBirth() != null) {
            lblCustomerDateOfBirth.setText(customer.getDateOfBirth().format(dateFormatter));
        } else {
            lblCustomerDateOfBirth.setText("null");
        }

        User user = this.contract.getUser();
        lblUserFullName.setText(user.getFullName());
        lblUserIdCard.setText(user.getIdCard());
        lblUserAddress.setText(user.getAddress());
        lblUserEmail.setText(user.getEmail());
        lblUserPhone.setText(user.getPhone());
        lblUserRole.setText(user.getRole());

        if (user.getDateOfBirth() != null) {
            lblUserDateOfBirth.setText(user.getDateOfBirth().format(dateFormatter));
        } else {
            lblUserDateOfBirth.setText("null");
        }

        DefaultTableModel tableModel = (DefaultTableModel) tblContractJob.getModel();
        tableModel.setRowCount(0);

        int cnt = 0;
        for (ContractJob cj : this.contract.getContractJobs()) {
            for (ContractJobShift cjs : cj.getContractJobShifts()) {
                tableModel.addRow(new Object[]{
                        ++cnt,
                        cj.getJob().getJobName(),
                        cjs.getShift().getWorkingDate().format(dateFormatter),
                        cjs.getShift().getStartTime().format(timeFormatter),
                        cjs.getShift().getEndTime().format(timeFormatter),
                        cjs.getRequiredWorkers(),
                        cjs.getAgreedWage()
                });
            }
        }

        lblPaymentMethod.setText(this.contract.getPaymentMethod());
        lblTotalWage.setText(String.format("%,.0f VND", this.contract.getTotalJobWage()));
        lblContractDate.setText(this.contract.getContractDate().format(dateFormatter));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCustomerFullName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCustomerIdCard = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCustomerDateOfBirth = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCustomerAddress = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCustomerEmail = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCustomerPhone = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCustomerType = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblUserFullName = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblUserIdCard = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblUserDateOfBirth = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblUserAddress = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblUserEmail = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblUserPhone = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblUserRole = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblContractJob = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        lblPaymentMethod = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblTotalWage = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblContractDate = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Xác nhận hợp đồng");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin khách hàng"));
        jPanel1.setLayout(new java.awt.GridLayout(7, 2));

        jLabel1.setText("Họ và tên:  ");
        jPanel1.add(jLabel1);

        lblCustomerFullName.setText("Nguyễn Thế Công");
        jPanel1.add(lblCustomerFullName);

        jLabel2.setText("CCCD:  ");
        jPanel1.add(jLabel2);

        lblCustomerIdCard.setText("038289123450");
        jPanel1.add(lblCustomerIdCard);

        jLabel3.setText("Ngày sinh:  ");
        jPanel1.add(jLabel3);

        lblCustomerDateOfBirth.setText("12/09/1989 ");
        jPanel1.add(lblCustomerDateOfBirth);

        jLabel4.setText("Địa chỉ:  ");
        jPanel1.add(jLabel4);

        lblCustomerAddress.setText("Hà Đông, Hà Nội ");
        jPanel1.add(lblCustomerAddress);

        jLabel5.setText("Email:  ");
        jPanel1.add(jLabel5);

        lblCustomerEmail.setText("congnt@gmail.com ");
        jPanel1.add(lblCustomerEmail);

        jLabel6.setText("SĐT:  ");
        jPanel1.add(jLabel6);

        lblCustomerPhone.setText("0373216789");
        jPanel1.add(lblCustomerPhone);

        jLabel7.setText("Phân loại:  ");
        jPanel1.add(jLabel7);

        lblCustomerType.setText("Gia đình");
        jPanel1.add(lblCustomerType);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"));
        jPanel2.setLayout(new java.awt.GridLayout(7, 2));

        jLabel8.setText("Họ và tên:  ");
        jPanel2.add(jLabel8);

        lblUserFullName.setText("Lê Văn An");
        jPanel2.add(lblUserFullName);

        jLabel9.setText("CCCD:  ");
        jPanel2.add(jLabel9);

        lblUserIdCard.setText("029200123456");
        jPanel2.add(lblUserIdCard);

        jLabel10.setText("Ngày sinh:  ");
        jPanel2.add(jLabel10);

        lblUserDateOfBirth.setText("19/01/2000");
        jPanel2.add(lblUserDateOfBirth);

        jLabel11.setText("Địa chỉ:  ");
        jPanel2.add(jLabel11);

        lblUserAddress.setText("Cầu Giấy, Hà Nội");
        jPanel2.add(lblUserAddress);

        jLabel12.setText("Email:  ");
        jPanel2.add(jLabel12);

        lblUserEmail.setText("anlv@gmail.com");
        jPanel2.add(lblUserEmail);

        jLabel13.setText("SĐT:  ");
        jPanel2.add(jLabel13);

        lblUserPhone.setText("0389317544");
        jPanel2.add(lblUserPhone);

        jLabel14.setText("Chức vụ:  ");
        jPanel2.add(jLabel14);

        lblUserRole.setText("Quản lí kinh doanh");
        jPanel2.add(lblUserRole);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách đầu việc/ca làm"));

        tblContractJob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên đầu việc", "Ngày làm", "Giờ bắt đầu", "Giờ kết thúc", "Số nhân công", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblContractJob);
        if (tblContractJob.getColumnModel().getColumnCount() > 0) {
            tblContractJob.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jPanel3.setLayout(new java.awt.GridLayout(1, 6));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Hình thức thanh toán:  ");
        jPanel3.add(jLabel17);

        lblPaymentMethod.setText("Tiền mặt");
        jPanel3.add(lblPaymentMethod);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Tổng tiền công:  ");
        jPanel3.add(jLabel16);

        lblTotalWage.setText("1.000.000 VND");
        jPanel3.add(lblTotalWage);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Ngày ký:  ");
        jPanel3.add(jLabel15);

        lblContractDate.setText("16/03/2026");
        jPanel3.add(lblContractDate);

        btnSave.setText("Lưu hợp đồng");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnBack.setText("Quay lại");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String oldStatus = this.contract.getStatus();
        this.contract.setStatus("Đã xác nhận");

        ContractDAO contractDAO = new ContractDAO();
        if (contractDAO.addContract(this.contract)) {
            JOptionPane.showMessageDialog(this, "Lưu hợp đồng thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            this.createContractFrm.dispose();
            this.dispose();
        } else {
            this.contract.setStatus(oldStatus);
            JOptionPane.showMessageDialog(this, "Lỗi khi lưu hợp đồng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblContractDate;
    private javax.swing.JLabel lblCustomerAddress;
    private javax.swing.JLabel lblCustomerDateOfBirth;
    private javax.swing.JLabel lblCustomerEmail;
    private javax.swing.JLabel lblCustomerFullName;
    private javax.swing.JLabel lblCustomerIdCard;
    private javax.swing.JLabel lblCustomerPhone;
    private javax.swing.JLabel lblCustomerType;
    private javax.swing.JLabel lblPaymentMethod;
    private javax.swing.JLabel lblTotalWage;
    private javax.swing.JLabel lblUserAddress;
    private javax.swing.JLabel lblUserDateOfBirth;
    private javax.swing.JLabel lblUserEmail;
    private javax.swing.JLabel lblUserFullName;
    private javax.swing.JLabel lblUserIdCard;
    private javax.swing.JLabel lblUserPhone;
    private javax.swing.JLabel lblUserRole;
    private javax.swing.JTable tblContractJob;
    // End of variables declaration//GEN-END:variables
}
