/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Contract;
import model.ContractJob;
import model.ContractJobShift;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

import static javax.swing.SwingUtilities.isRightMouseButton;

/**
 *
 * @author HoangHoangTuan
 */
public class CreateContractFrm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateContractFrm.class.getName());
    private Contract contract;
    private ArrayList<ContractJob> contractJobs = new ArrayList<>();
    DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm");

    /**
     * Creates new form CreateContractFrm
     */
    public CreateContractFrm(Contract contract) {
        this.contract = contract;
        this.contractJobs = this.contract.getContractJobs();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblContractJob = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnAddJob = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnConfirmContract = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        cbxPaymentMethod = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lập hợp đồng - KH: " + this.contract.getCustomer().getFullName());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách đầu việc/ca làm"));

        tblContractJob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên đầu việc", "Ngày làm", "Giờ bắt đầu", "Giờ kết thúc", "Số nhân công", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContractJob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContractJobMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblContractJob);
        if (tblContractJob.getColumnModel().getColumnCount() > 0) {
            tblContractJob.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jLabel8.setText("Để thêm đầu việc mới, click Thêm.");

        btnAddJob.setText("Thêm");
        btnAddJob.addActionListener(this::btnAddJobActionPerformed);

        jLabel9.setText("Hình thức thanh toán:");

        btnConfirmContract.setText("Xác nhận hợp đồng");
        btnConfirmContract.addActionListener(this::btnConfirmContractActionPerformed);

        btnBack.setText("Quay lại");
        btnBack.addActionListener(this::btnBackActionPerformed);

        cbxPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chuyển khoản qua Công ty", "Tiền mặt tại văn phòng Công ty", "Thanh toán cho nhân công" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddJob))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfirmContract)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxPaymentMethod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btnAddJob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbxPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnConfirmContract))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJobActionPerformed
        // TODO add your handling code here:
        SearchJobFrm searchJobFrm = new SearchJobFrm(this, this.contract);
        searchJobFrm.setVisible(true);
    }//GEN-LAST:event_btnAddJobActionPerformed

    private void btnConfirmContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmContractActionPerformed
        // TODO add your handling code here:
        if (this.contractJobs.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng thêm ít nhất một đầu việc vào hợp đồng.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        this.contract.setPaymentMethod(cbxPaymentMethod.getSelectedItem().toString());
        this.contract.setContractDate(java.time.LocalDate.now());

        ConfirmContractFrm confirmContractFrm = new ConfirmContractFrm(this, this.contract);
        confirmContractFrm.setVisible(true);
    }//GEN-LAST:event_btnConfirmContractActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblContractJobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContractJobMouseClicked
        // TODO add your handling code here:
        int row = tblContractJob.rowAtPoint(evt.getPoint());

        if (row == -1) {
            return;
        }

        tblContractJob.setRowSelectionInterval(row, row);

        if (isRightMouseButton(evt)) {
            JPopupMenu popupMenu = new JPopupMenu();
            JMenuItem itemDelete = new JMenuItem("Xoá");
            popupMenu.add(itemDelete);
            popupMenu.show(tblContractJob, evt.getX(), evt.getY());

            itemDelete.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent e) {
                    if (JOptionPane.showConfirmDialog(CreateContractFrm.this, "Bạn có xác nhận xoá ca làm này?", "Xác nhận", JOptionPane.YES_NO_OPTION) == 0) {
                        deleleShiftAtRow(row);
                    }
                }
            });
        }
    }//GEN-LAST:event_tblContractJobMouseClicked

    public void deleleShiftAtRow(int row) {
        int index = 0;
        ContractJob contractJob = null;
        ContractJobShift contractJobShift = null;

        for (ContractJob cj : this.contractJobs) {
            for (ContractJobShift cjs : cj.getContractJobShifts()) {
                if (row == index) {
                    contractJob = cj;
                    contractJobShift = cjs;
                    break;
                }
                ++index;
            }
            if (contractJobShift != null) {
                break;
            }
        }

        if (contractJob != null && contractJobShift != null) {
            contractJob.getContractJobShifts().remove(contractJobShift);
            if (contractJob.getContractJobShifts().isEmpty()) {
                this.contractJobs.remove(contractJob);
            }
        }
        reloadTblContractJob();
    }

    public void reloadTblContractJob() {
        DefaultTableModel tableModel = (DefaultTableModel) tblContractJob.getModel();
        tableModel.setRowCount(0);

        int cnt = 0;
        for (ContractJob cj : this.contractJobs) {
            for (ContractJobShift cjs : cj.getContractJobShifts()) {
                tableModel.addRow(new Object[]{
                        ++cnt,
                        cj.getJob().getJobName(),
                        cjs.getShift().getWorkingDate().format(dateFormatter),
                        cjs.getShift().getStartTime().format(timeFormatter),
                        cjs.getShift().getEndTime().format(timeFormatter),
                        cjs.getRequiredWorkers(),
                        String.format("%,.0f VNĐ", cjs.getAgreedWage())
                });
            }
        }
    }

    public Contract getContract() {
        return contract;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddJob;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirmContract;
    private javax.swing.JComboBox<String> cbxPaymentMethod;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblContractJob;
    // End of variables declaration//GEN-END:variables
}
