/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.User;
import model.User;

import java.time.format.DateTimeFormatter;

/**
 *
 * @author HoangHoangTuan
 */
public class SalesManagerHomeFrm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SalesManagerHomeFrm.class.getName());
    private User user;
    DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    /**
     * Creates new form SalesManagerHomeFrm
     */
    public SalesManagerHomeFrm(User user) {
        this.user = user;
        initComponents();
        this.setLocationRelativeTo(null);

        lblFullName.setText(user.getFullName());
        lblIdCard.setText(user.getIdCard());
        lblDateOfBirth.setText(user.getDateOfBirth().format(dateFormatter));
        lblAddress.setText(user.getAddress());
        lblEmail.setText(user.getEmail());
        lblPhone.setText(user.getPhone());
        lblRole.setText(user.getRole());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblIdCard = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        btnSignContract = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang chủ");
        setResizable(false);

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"));
        mainPanel.setLayout(new java.awt.GridLayout(7, 2));

        jLabel1.setText("Họ và tên:  ");
        mainPanel.add(jLabel1);

        lblFullName.setText(" ");
        mainPanel.add(lblFullName);

        jLabel2.setText("CCCD:  ");
        mainPanel.add(jLabel2);

        lblIdCard.setText(" ");
        mainPanel.add(lblIdCard);

        jLabel3.setText("Ngày sinh:  ");
        mainPanel.add(jLabel3);

        lblDateOfBirth.setText(" ");
        mainPanel.add(lblDateOfBirth);

        jLabel4.setText("Địa chỉ:  ");
        mainPanel.add(jLabel4);

        lblAddress.setText(" ");
        mainPanel.add(lblAddress);

        jLabel5.setText("Email:  ");
        mainPanel.add(jLabel5);

        lblEmail.setText(" ");
        mainPanel.add(lblEmail);

        jLabel6.setText("SĐT:  ");
        mainPanel.add(jLabel6);

        lblPhone.setText(" ");
        mainPanel.add(lblPhone);

        jLabel7.setText("Chức vụ:  ");
        mainPanel.add(jLabel7);

        lblRole.setText(" ");
        mainPanel.add(lblRole);

        btnSignContract.setText("Ký hợp đồng với khách hàng");
        btnSignContract.addActionListener(this::btnSignContractActionPerformed);

        btnLogout.setText("Đăng xuất");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 68, Short.MAX_VALUE)
                        .addComponent(btnSignContract)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout))
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignContract)
                    .addComponent(btnLogout))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignContractActionPerformed
        // TODO add your handling code here:
        SearchCustomerFrm searchCustomerFrm = new SearchCustomerFrm(this.user);
        searchCustomerFrm.setVisible(true);
    }//GEN-LAST:event_btnSignContractActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginFrm loginFrm = new LoginFrm();
        loginFrm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSignContract;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblIdCard;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRole;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
