/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.JobDAO;
import model.Contract;
import model.ContractJob;
import model.Job;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

import static javax.swing.SwingUtilities.isLeftMouseButton;

/**
 *
 * @author HoangHoangTuan
 */
public class SearchJobFrm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchJobFrm.class.getName());
    private CreateContractFrm createContractFrm;
    private Contract contract;
    private ArrayList<Job> jobs = new ArrayList<>();

    /**
     * Creates new form SearchJobView
     */
    public SearchJobFrm(CreateContractFrm createContractFrm, Contract contract) {
        this.createContractFrm = createContractFrm;
        this.contract = contract;
        initComponents();
        this.setLocationRelativeTo(null);

        JobDAO jobDAO = new JobDAO();
        this.jobs = jobDAO.searchJob("");

        DefaultTableModel tableModel = (DefaultTableModel) tblJob.getModel();
        tableModel.setRowCount(0);

        int cnt = 0;
        for (Job j : this.jobs) {
            tableModel.addRow(new Object[]{
                    ++cnt,
                    j.getJobName(),
                    j.getDescription(),
                    j.getSkill()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtJobKey = new javax.swing.JTextField();
        btnSearchJob = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJob = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAddJob = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tìm đầu việc");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm đầu việc"));

        txtJobKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJobKeyKeyPressed(evt);
            }
        });

        btnSearchJob.setText("Tìm kiếm");
        btnSearchJob.addActionListener(this::btnSearchJobActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtJobKey)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchJob)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJobKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchJob))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kết quả tìm kiếm"));

        tblJob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên đầu việc", "Mô tả", "Yêu cầu kĩ năng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblJob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJobMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblJob);
        if (tblJob.getColumnModel().getColumnCount() > 0) {
            tblJob.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jLabel1.setText("Để thêm đầu việc mới, click Thêm.");

        btnAddJob.setText("Thêm");
        btnAddJob.addActionListener(this::btnAddJobActionPerformed);

        btnBack.setText("Quay lại");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddJob)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddJob)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchJobActionPerformed
        // TODO add your handling code here:
        String key = txtJobKey.getText().trim();

        JobDAO jobDAO = new JobDAO();
        this.jobs = jobDAO.searchJob(key);

        DefaultTableModel tableModel = (DefaultTableModel) tblJob.getModel();
        tableModel.setRowCount(0);

        int cnt = 0;
        for (Job j : this.jobs) {
            tableModel.addRow(new Object[]{
                    ++cnt,
                    j.getJobName(),
                    j.getDescription(),
                    j.getSkill()
            });
        }
    }//GEN-LAST:event_btnSearchJobActionPerformed

    private void txtJobKeyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJobKeyKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnSearchJob.doClick();
        }
    }//GEN-LAST:event_txtJobKeyKeyPressed

    private void btnAddJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJobActionPerformed
        // TODO add your handling code here:
        AddJobFrm addJobFrm = new AddJobFrm(this.contract.getUser());
        addJobFrm.setVisible(true);
    }//GEN-LAST:event_btnAddJobActionPerformed

    private void tblJobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJobMouseClicked
        // TODO add your handling code here:
        int row = tblJob.rowAtPoint(evt.getPoint());

        if (row == -1) {
            return;
        }

        tblJob.setRowSelectionInterval(row, row);

        if (isLeftMouseButton(evt) && evt.getClickCount() == 2) {
            Job job = this.jobs.get(row);

            ContractJob contractJob = new ContractJob();
            contractJob.setJob(job);

            AddShiftFrm addShiftFrm = new AddShiftFrm(this.createContractFrm, this.contract, contractJob);
            addShiftFrm.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_tblJobMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddJob;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearchJob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblJob;
    private javax.swing.JTextField txtJobKey;
    // End of variables declaration//GEN-END:variables
}
